import React from 'react'

const Course = [
{
  "id": 2,
  "title": "HTML, CSS từ Zero đến Hero",
  "slug": "html-css",
  "description": "Trong khóa này chúng ta sẽ cùng nhau xây dựng giao diện 2 trang web là The Band & Shopee.",
  "thumbnail": "courses/2.png",
  "content": null,
  "preview_origin": "youtube",
  "preview_youtube_id": "R6plN3FvzFY",
  "preview_path": null,
  "language": "html",
  "syntax_highligh": "language-html",
  "level": "Trình độ cơ bản",
  "priority": 10,
  "students_count": 79527,
  "deleted_at": null,
  "created_at": "2020-04-10T14:23:13.000000Z",
  "updated_at": "2021-11-25T04:24:40.000000Z",
  "thumbnail_cdn": "https://cdn.fullstack.edu.vn/f8-learning/courses/2.png"
},
{
  "id": 1,
  "title": "JavaScript Cơ Bản",
  "slug": "javascript-co-ban",
  "description": "Học Javascript cơ bản phù hợp cho người chưa từng học lập trình. Với hơn 100 bài học và có bài tập thực hành sau mỗi bài học.",
  "thumbnail": "courses/1.png",
  "content": null,
  "preview_origin": "youtube",
  "preview_youtube_id": "0SJE9dYdpps",
  "preview_path": null,
  "language": "javascript",
  "syntax_highligh": "language-javascript",
  "level": "Trình độ cơ bản",
  "priority": 30,
  "students_count": 51045,
  "deleted_at": null,
  "created_at": "2020-06-10T14:23:13.000000Z",
  "updated_at": "2021-11-25T04:28:32.000000Z",
  "thumbnail_cdn": "https://cdn.fullstack.edu.vn/f8-learning/courses/1.png"
},
{
  "id": 7,
  "title": "Kiến Thức Nhập Môn",
  "slug": "lessons-for-newbie",
  "description": "Để có cái nhìn tổng quan về ngành IT - Lập trình web các bạn nên xem các videos tại khóa này trước nhé.",
  "thumbnail": "courses/7.png",
  "content": null,
  "preview_origin": "youtube",
  "preview_youtube_id": "M62l1xA5Eu8",
  "preview_path": null,
  "language": null,
  "syntax_highligh": null,
  "level": "Trình độ cơ bản",
  "priority": 0,
  "students_count": 37627,
  "deleted_at": null,
  "created_at": "2020-02-10T14:23:13.000000Z",
  "updated_at": "2021-11-25T04:24:50.000000Z",
  "thumbnail_cdn": "https://cdn.fullstack.edu.vn/f8-learning/courses/7.png"
},
{
  "id": 3,
  "title": "Responsive Với Grid System",
  "slug": "responsive-web-design",
  "description": "Trong khóa này chúng ta sẽ học về cách xây dựng giao diện web responsive với Grid System, tương tự Bootstrap 4.",
  "thumbnail": "courses/3.png",
  "content": null,
  "preview_origin": "youtube",
  "preview_youtube_id": "uz5LIP85J5Y",
  "preview_path": null,
  "language": "html",
  "syntax_highligh": "language-html",
  "level": "Trình độ cơ bản",
  "priority": 20,
  "students_count": 15608,
  "deleted_at": null,
  "created_at": "2020-05-10T14:23:13.000000Z",
  "updated_at": "2021-11-25T04:22:49.000000Z",
  "thumbnail_cdn": "https://cdn.fullstack.edu.vn/f8-learning/courses/3.png"
},
{
  "id": 6,
  "title": "Node & ExpressJS",
  "slug": "nodejs",
  "description": "Học Back-end với Node & ExpressJS framework, hiểu các khái niệm khi làm Back-end và xây dựng RESTful API cho trang web.",
  "thumbnail": "courses/6.png",
  "content": null,
  "preview_origin": "youtube",
  "preview_youtube_id": "z2f7RHgvddc",
  "preview_path": null,
  "language": "javascript",
  "syntax_highligh": "language-javascript",
  "level": "Trình độ cơ bản",
  "priority": 32,
  "students_count": 13515,
  "deleted_at": null,
  "created_at": "2020-08-01T14:23:13.000000Z",
  "updated_at": "2021-11-25T04:26:04.000000Z",
  "thumbnail_cdn": "https://cdn.fullstack.edu.vn/f8-learning/courses/6.png"
},
{
  "id": 5,
  "title": "HTML, CSS Tips & Tricks",
  "slug": "html-css-tutorials",
  "description": "Tutorials về HTML, CSS, UI, UX sẽ được tổng hợp tại khóa học này, các video có nội dung ngắn gọn, súc tích giúp học viên có thể ứng dụng ngay vào thực tế",
  "thumbnail": "courses/5.png",
  "content": null,
  "preview_origin": "youtube",
  "preview_youtube_id": "nB6cJh_bb1U",
  "preview_path": null,
  "language": "html",
  "syntax_highligh": "language-html",
  "level": "Trình độ cơ bản",
  "priority": 40,
  "students_count": 10183,
  "deleted_at": null,
  "created_at": "2020-03-10T14:23:13.000000Z",
  "updated_at": "2021-11-25T03:44:33.000000Z",
  "thumbnail_cdn": "https://cdn.fullstack.edu.vn/f8-learning/courses/5.png"
}


]
 
 export default Course;